const SYSTEM_PROMPT = `
You are an expert IELTS examiner. Your task is to evaluate a student's speaking video based on a specific topic and provide detailed feedback.

The feedback MUST strictly follow this JSON format:
{
  "general": "Greeting and overall impression...",
  "fluency": "Detailed feedback on Fluency and Coherence...",
  "fluency_score": 6.0,
  "grammar": "Detailed feedback on Grammatical Range and Accuracy...",
  "grammar_score": 6.0,
  "lexical": "Detailed feedback on Lexical Resource...",
  "lexical_score": 6.0,
  "pronunciation": "Detailed feedback on Pronunciation...",
  "pronunciation_score": 6.0
}

IMPORTANT RUBRIC & STYLE GUIDE:
Base your feedback tone on standard IELTS speaking descriptors. Be constructive, professional, and provide specific examples for improvement:

- [General]: Provide a warm greeting and an overview of the student's performance. Highlight key strengths and main areas for improvement.
- [Fluency]: Comment on the speaker's speed, hesitation, coherence, and use of connective devices.
- [Grammar]: Evaluate grammatical accuracy and the range of simple vs. complex structures. Note specific recurring errors.
- [Lexical]: Assess the vocabulary range. Suggest 3-5 specific advanced vocabulary words or idioms related to the topic that the student could have used.
- [Pronunciation]: Address intonation, word stress, and clarity of specific phonemes.

Return ONLY the raw JSON object, no markdown code blocks around it. Ensure the scores are numbers (e.g., 5.0, 5.5, 6.0, up to 9.0).
`;

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.action === "generate_feedback") {
        
        chrome.storage.local.get(['geminiApiKey'], async (result) => {
            const apiKey = result.geminiApiKey;
            if (!apiKey) {
                sendResponse({ error: "API Key not found. Please click the Extension icon and enter your Gemini API Key in the settings." });
                return;
            }

            try {
                // Call Gemini API
                const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${apiKey}`;
                
                const requestBody = {
                    "contents": [
                        {
                            "parts": [
                                { "text": SYSTEM_PROMPT },
                                { "text": "Assignment Topic: " + request.topicText },
                                { "text": "Please analyze this YouTube video and grade it: " + request.videoUrl }
                            ]
                        }
                    ],
                    "generationConfig": {
                        "temperature": 0.2,
                        "response_mime_type": "application/json"
                    }
                };

                const response = await fetch(apiUrl, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(requestBody)
                });

                const data = await response.json();
                
                if (data.error) {
                    throw new Error(data.error.message || "Unknown API Error");
                }

                if (data.candidates && data.candidates.length > 0) {
                    const aiText = data.candidates[0].content.parts[0].text;
                    sendResponse({ feedback: aiText });
                } else {
                    throw new Error("No response generated by AI.");
                }

            } catch (error) {
                console.error("Gemini API Error:", error);
                
                // If it's a model error, try to fetch the list of valid models
                if (error.message.includes("is not found") || error.message.includes("is not supported")) {
                    try {
                        const modelsUrl = `https://generativelanguage.googleapis.com/v1beta/models?key=${apiKey}`;
                        const mRes = await fetch(modelsUrl);
                        const mData = await mRes.json();
                        const validModels = mData.models.map(m => m.name.replace('models/', '')).join(', ');
                        sendResponse({ error: `Model error. Your key supports these models: ${validModels}` });
                        return;
                    } catch (e) {}
                }
                
                sendResponse({ error: error.message });
            }
        });

        return true; // Keep message channel open for async response
    }
});
